-- New API v1.0.0-rc.27
-- PostgreSQL 15 users table DDL generated by the application's GORM migration.

CREATE TABLE public.users (
    id bigint NOT NULL,
    username text,
    password text NOT NULL,
    display_name text,
    role bigint DEFAULT 1,
    status bigint DEFAULT 1,
    email text,
    github_id text,
    discord_id text,
    oidc_id text,
    wechat_id text,
    telegram_id text,
    access_token character(32),
    quota bigint DEFAULT 0,
    used_quota bigint DEFAULT 0,
    request_count bigint DEFAULT 0,
    "group" character varying(64) DEFAULT 'default'::character varying,
    aff_code character varying(32),
    aff_count bigint DEFAULT 0,
    aff_quota bigint DEFAULT 0,
    aff_history bigint DEFAULT 0,
    inviter_id bigint,
    deleted_at timestamp with time zone,
    linux_do_id text,
    setting text,
    remark character varying(255),
    stripe_customer character varying(64),
    created_at bigint,
    last_login_at bigint DEFAULT 0,
    auth_version bigint DEFAULT 1 NOT NULL
);

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;

ALTER TABLE ONLY public.users
    ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);

CREATE UNIQUE INDEX idx_users_access_token ON public.users USING btree (access_token);
CREATE UNIQUE INDEX idx_users_aff_code ON public.users USING btree (aff_code);
CREATE INDEX idx_users_deleted_at ON public.users USING btree (deleted_at);
CREATE INDEX idx_users_discord_id ON public.users USING btree (discord_id);
CREATE INDEX idx_users_display_name ON public.users USING btree (display_name);
CREATE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_users_git_hub_id ON public.users USING btree (github_id);
CREATE INDEX idx_users_inviter_id ON public.users USING btree (inviter_id);
CREATE INDEX idx_users_linux_do_id ON public.users USING btree (linux_do_id);
CREATE INDEX idx_users_oidc_id ON public.users USING btree (oidc_id);
CREATE INDEX idx_users_stripe_customer ON public.users USING btree (stripe_customer);
CREATE INDEX idx_users_telegram_id ON public.users USING btree (telegram_id);
CREATE INDEX idx_users_username ON public.users USING btree (username);
CREATE INDEX idx_users_we_chat_id ON public.users USING btree (wechat_id);
